servers:
  c:
    - ccls
    - --init="{\"clang\": {\"resourceDir\": \"/usr/lib/llvm-10/lib/clang/10.0.0/include\"}}"
  c++:
    - ccls
    - --init="{\"clang\": {\"resourceDir\": \"/usr/lib/llvm-10/lib/clang/10.0.0/include\"}}"
  css:
    - css-languageserver
    - --stdio
  dockerfile:
    - docker-langserver
    - --stdio
  go:
    - gopls
  html:
    - html-languageserver
    - --stdio
  java:
    - python3.9
    - jdtls
    - --configuration ~/.cache/jdtls
  javascript:
    - node
    - /home/craftslab/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js
  python:
    - pylsp
  rust:
    - rls
  shell:
    - bash-language-server
    - start
