servers:
  c:
    - ccls
    - --init
    - "{\"clang\": {\"resourceDir\": \"/usr/lib/llvm-10/lib/clang/10.0.0/include\"}}"
  c++:
    - ccls
    - --init
    - "{\"clang\": {\"resourceDir\": \"/usr/lib/llvm-10/lib/clang/10.0.0/include\"}}"
  css:
    - css-languageserver
    - --stdio
  dockerfile:
    - docker-langserver
    - --stdio
  go:
    - gopls
  html:
    - html-languageserver
    - --stdio
  java:
    - python3.9
    - jdt-language-server/bin/jdtls
    - --configuration ~/.cache/jdtls
  javascript:
    - javascript-typescript-stdio
  python:
    - pylsp
  rust:
    - .cargo/bin/rls
  shell:
    - bash-language-server
    - start
